// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ur_9UZxkDnuzdJFU2P7yYAXwVRHJZUk',
    appId: '1:812104252403:web:7ad7ddd963728ff7d4f086',
    messagingSenderId: '812104252403',
    projectId: 'chatapp-ecadd',
    authDomain: 'chatapp-ecadd.firebaseapp.com',
    storageBucket: 'chatapp-ecadd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBapItdeXqziKRU7mkGM_uRYbbZhHEQzWk',
    appId: '1:812104252403:android:50ac2faf0edef11ad4f086',
    messagingSenderId: '812104252403',
    projectId: 'chatapp-ecadd',
    storageBucket: 'chatapp-ecadd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqo2JINbWcDNLKHR-rE7GFSsnxK83p1Jg',
    appId: '1:812104252403:ios:51736d70dd927a16d4f086',
    messagingSenderId: '812104252403',
    projectId: 'chatapp-ecadd',
    storageBucket: 'chatapp-ecadd.appspot.com',
    iosClientId: '812104252403-btad29hantvjka0h7bsqv54dfsg833sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
